definitions:
  model.ClientCredential:
    properties:
      apiKey:
        type: string
    type: object
  model.TryPayUserOpRequest:
    properties:
      extra: {}
      force_entrypoint_address:
        type: string
      force_network:
        $ref: '#/definitions/types.NetWork'
      force_strategy_id:
        type: string
      force_token:
        type: string
      user_operation:
        $ref: '#/definitions/model.UserOperationItem'
    type: object
  model.UserOperationItem:
    properties:
      call_data:
        type: string
      call_gas_limit:
        type: string
      init_code:
        type: string
      max_fee_per_gas:
        type: string
      max_priority_fee_per_gas:
        type: string
      nonce:
        type: string
      per_verification_gas:
        type: string
      sender:
        type: string
      signature:
        type: string
      verification_gas_list:
        type: string
    required:
    - call_data
    - call_gas_limit
    - max_fee_per_gas
    - max_priority_fee_per_gas
    - nonce
    - per_verification_gas
    - sender
    - verification_gas_list
    type: object
  types.NetWork:
    enum:
    - ethereum
    - sepolia
    - arbitrum
    type: string
    x-enum-varnames:
    - Ethereum
    - Sepolia
    - Arbitrum
info:
  contact:
    name: AAStar Support
    url: https://aastar.xyz
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      description: Get AccessToken By ApiKey
      parameters:
      - description: AccessToken Model
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/model.ClientCredential'
      responses:
        "200":
          description: OK
      tags:
      - Auth
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Get Healthz
      responses:
        "200":
          description: OK
      tags:
      - Healthz
  /api/v1/get-support-entrypoint:
    get:
      consumes:
      - application/json
      description: get the support entrypoint
      parameters:
      - description: network
        in: query
        name: network
        type: string
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - Sponsor
  /api/v1/get-support-strategy:
    get:
      consumes:
      - application/json
      description: get the support strategy
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - Sponsor
  /api/v1/try-pay-user-operation:
    post:
      consumes:
      - application/json
      description: sponsor the userOp
      parameters:
      - description: UserOp Request
        in: body
        name: tryPay
        required: true
        schema:
          $ref: '#/definitions/model.TryPayUserOpRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - Sponsor
securityDefinitions:
  JWT:
    description: Type 'Bearer \<TOKEN\>' to correctly set the AccessToken
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
