basePath: /api
definitions:
  model.DepositSponsorRequest:
    properties:
      deposit_address:
        type: string
      deposit_source:
        type: string
      is_test_net:
        type: boolean
      pay_user_id:
        type: string
      time_stamp:
        type: integer
      tx_hash:
        type: string
    type: object
  model.JsonRpcRequest:
    properties:
      id:
        type: integer
      jsonrpc:
        type: string
      method:
        type: string
      params:
        items: {}
        type: array
    type: object
  model.WithdrawSponsorRequest:
    properties:
      amount:
        type: number
      deposit_source:
        type: string
      isTestNet:
        type: boolean
      payUserId:
        type: string
      refund_address:
        type: string
      time_stamp:
        type: integer
      withdraw_source:
        type: string
    type: object
info:
  contact:
    name: AAStar Support
    url: https://aastar.xyz
paths:
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Get Healthz
      responses:
        "200":
          description: OK
      tags:
      - Healthz
  /api/v1/paymaster/{network}:
    post:
      consumes:
      - application/json
      description: Paymaster JSON-RPC API
      parameters:
      - description: Network
        in: path
        name: network
        required: true
        type: string
      - description: JsonRpcRequest Model
        in: body
        name: rpcRequest
        required: true
        schema:
          $ref: '#/definitions/model.JsonRpcRequest'
      - description: apiKey
        in: query
        name: apiKey
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - Paymaster
  /api/v1/paymaster_sponsor/deposit:
    post:
      consumes:
      - application/json
      description: Deposit Sponsor
      parameters:
      - description: DepositSponsorRequest Model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.DepositSponsorRequest'
      - description: relay Request  Body Hash
        in: header
        name: relay_hash
        type: string
      - description: relay Request  Body Hash
        in: header
        name: relay_signature
        type: string
      responses:
        "200":
          description: OK
      tags:
      - DepositSponsor
  /api/v1/paymaster_sponsor/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraw Sponsor
      parameters:
      - description: WithdrawSponsorRequest Model
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.WithdrawSponsorRequest'
      - description: Is Test Net
        in: path
        name: is_test_net
        required: true
        type: boolean
      responses:
        "200":
          description: OK
      tags:
      - Sponsor
swagger: "2.0"
