definitions:
  model.ClientCredential:
    properties:
      apiKey:
        type: string
    type: object
  model.JsonRpcRequest:
    properties:
      id:
        type: integer
      jsonrpc:
        type: string
      method:
        type: string
      params:
        items: {}
        type: array
    type: object
info:
  contact:
    name: AAStar Support
    url: https://aastar.xyz
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      description: Get AccessToken By ApiKey
      parameters:
      - description: AccessToken Model
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/model.ClientCredential'
      responses:
        "200":
          description: OK
      tags:
      - Auth
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Get Healthz
      responses:
        "200":
          description: OK
      tags:
      - Healthz
  /api/v1/paymaster{network}:
    post:
      consumes:
      - application/json
      description: Paymaster JSON-RPC API
      parameters:
      - description: Network
        in: path
        name: network
        required: true
        type: string
      - description: JsonRpcRequest Model
        in: body
        name: rpcRequest
        required: true
        schema:
          $ref: '#/definitions/model.JsonRpcRequest'
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - Paymaster
securityDefinitions:
  JWT:
    description: Type 'Bearer \<TOKEN\>' to correctly set the AccessToken
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
