definitions:
  models.ClientCredential:
    properties:
      apiKey:
        type: string
    type: object
info:
  contact:
    name: AAStar Support
    url: https://aastar.xyz
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      description: Get AccessToken By ApiKey
      parameters:
      - description: AccessToken Model
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/models.ClientCredential'
      responses:
        "200":
          description: OK
      tags:
      - Auth
  /api/healthz:
    get:
      description: Get Healthz
      responses:
        "200":
          description: OK
      tags:
      - Healthz
  /api/v1/get-support-entrypoint:
    get:
      consumes:
      - application/json
      description: get the support entrypoint
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - Sponsor
  /api/v1/get-support-strategy:
    get:
      consumes:
      - application/json
      description: get the support strategy
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - Sponsor
  /api/v1/try-pay-user-operation:
    post:
      consumes:
      - application/json
      description: sponsor the userOp
      responses:
        "200":
          description: OK
      security:
      - JWT: []
      tags:
      - Sponsor
securityDefinitions:
  JWT:
    description: Type 'Bearer \<TOKEN\>' to correctly set the AccessToken
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
