on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'
      - name: Build
        run: go build -v ./...
      - name: Audit
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...
      - name: Test
        run: go test -v ./...
      - name: Swagger
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g ./cmd/server/main.go
          git config user.name devops
          git config suer.email devops@aastar.xyz
          git add .
          git commit -m "swagger updated"
          git push


name: Building And Testing
